-- Kavora CRM — initial schema
-- Generated by Drizzle Kit; includes pgvector + custom indexes that Drizzle
-- doesn't (yet) emit from its TS schema.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ─── Enums ────────────────────────────────────────────────────────────────────

CREATE TYPE "user_role" AS ENUM ('owner', 'admin', 'member');
CREATE TYPE "contact_status" AS ENUM ('lead', 'active', 'customer', 'archived');
CREATE TYPE "deal_status" AS ENUM ('open', 'won', 'lost');
CREATE TYPE "call_direction" AS ENUM ('inbound', 'outbound');
CREATE TYPE "call_status" AS ENUM (
  'queued', 'ringing', 'in-progress', 'completed', 'busy', 'failed', 'no-answer'
);
CREATE TYPE "sms_direction" AS ENUM ('inbound', 'outbound');
CREATE TYPE "sms_status" AS ENUM (
  'queued', 'sending', 'sent', 'delivered', 'read', 'failed'
);
CREATE TYPE "activity_type" AS ENUM (
  'call', 'sms', 'note', 'email', 'meeting', 'stage-change'
);
CREATE TYPE "ai_draft_channel" AS ENUM ('email', 'sms');
CREATE TYPE "phone_number_status" AS ENUM ('active', 'released');

-- ─── Tables ───────────────────────────────────────────────────────────────────

CREATE TABLE "organizations" (
  "id" varchar(64) PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "organizations_name_idx" ON "organizations" ("name");

CREATE TABLE "users" (
  "id" varchar(64) PRIMARY KEY,
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "email" text NOT NULL,
  "name" text,
  "image_url" text,
  "role" "user_role" NOT NULL DEFAULT 'member',
  "phone_for_routing" varchar(32),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "users_org_idx" ON "users" ("org_id");
CREATE UNIQUE INDEX "users_email_idx" ON "users" ("email");

CREATE TABLE "companies" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "domain" text,
  "industry" text,
  "size" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "companies_org_idx" ON "companies" ("org_id");
CREATE UNIQUE INDEX "companies_org_domain_idx" ON "companies" ("org_id", "domain");

CREATE TABLE "contacts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "first_name" text NOT NULL,
  "last_name" text,
  "email" text,
  "phone" varchar(32),
  "company_id" uuid REFERENCES "companies"("id") ON DELETE SET NULL,
  "source" text,
  "status" "contact_status" NOT NULL DEFAULT 'lead',
  "owner_user_id" varchar(64) REFERENCES "users"("id") ON DELETE SET NULL,
  "profile_notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "contacts_org_idx" ON "contacts" ("org_id");
CREATE UNIQUE INDEX "contacts_org_phone_idx" ON "contacts" ("org_id", "phone");
CREATE INDEX "contacts_org_email_idx" ON "contacts" ("org_id", "email");
CREATE INDEX "contacts_owner_idx" ON "contacts" ("owner_user_id");

CREATE TABLE "pipelines" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "pipelines_org_idx" ON "pipelines" ("org_id");

CREATE TABLE "pipeline_stages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "pipeline_id" uuid NOT NULL REFERENCES "pipelines"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "order" integer NOT NULL DEFAULT 0,
  "is_won" boolean NOT NULL DEFAULT false,
  "is_lost" boolean NOT NULL DEFAULT false,
  "color" varchar(16)
);
CREATE INDEX "stages_pipeline_idx" ON "pipeline_stages" ("pipeline_id");
CREATE UNIQUE INDEX "stages_pipeline_order_idx" ON "pipeline_stages" ("pipeline_id", "order");

CREATE TABLE "deals" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "title" text NOT NULL,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE SET NULL,
  "company_id" uuid REFERENCES "companies"("id") ON DELETE SET NULL,
  "pipeline_id" uuid NOT NULL REFERENCES "pipelines"("id") ON DELETE RESTRICT,
  "stage_id" uuid NOT NULL REFERENCES "pipeline_stages"("id") ON DELETE RESTRICT,
  "value_cents" integer NOT NULL DEFAULT 0,
  "currency" varchar(3) NOT NULL DEFAULT 'USD',
  "status" "deal_status" NOT NULL DEFAULT 'open',
  "owner_user_id" varchar(64) REFERENCES "users"("id") ON DELETE SET NULL,
  "expected_close_date" timestamptz,
  "closed_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "deals_org_idx" ON "deals" ("org_id");
CREATE INDEX "deals_org_stage_idx" ON "deals" ("org_id", "stage_id");
CREATE INDEX "deals_contact_idx" ON "deals" ("contact_id");
CREATE INDEX "deals_company_idx" ON "deals" ("company_id");

CREATE TABLE "tags" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "color" varchar(16)
);
CREATE UNIQUE INDEX "tags_org_name_idx" ON "tags" ("org_id", "name");

CREATE TABLE "contact_tags" (
  "contact_id" uuid NOT NULL REFERENCES "contacts"("id") ON DELETE CASCADE,
  "tag_id" uuid NOT NULL REFERENCES "tags"("id") ON DELETE CASCADE,
  PRIMARY KEY ("contact_id", "tag_id")
);

CREATE TABLE "notes" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE CASCADE,
  "deal_id" uuid REFERENCES "deals"("id") ON DELETE CASCADE,
  "author_user_id" varchar(64) REFERENCES "users"("id") ON DELETE SET NULL,
  "body" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "notes_contact_idx" ON "notes" ("contact_id");
CREATE INDEX "notes_deal_idx" ON "notes" ("deal_id");

CREATE TABLE "phone_numbers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "twilio_sid" varchar(64) NOT NULL,
  "number" varchar(32) NOT NULL,
  "friendly_name" text,
  "capabilities" jsonb,
  "voice_url" text,
  "sms_url" text,
  "status" "phone_number_status" NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "phone_numbers_twilio_sid_idx" ON "phone_numbers" ("twilio_sid");
CREATE UNIQUE INDEX "phone_numbers_number_idx" ON "phone_numbers" ("number");

CREATE TABLE "calls" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE SET NULL,
  "deal_id" uuid REFERENCES "deals"("id") ON DELETE SET NULL,
  "phone_number_id" uuid REFERENCES "phone_numbers"("id") ON DELETE SET NULL,
  "twilio_call_sid" varchar(64) NOT NULL,
  "direction" "call_direction" NOT NULL,
  "from_number" varchar(32) NOT NULL,
  "to_number" varchar(32) NOT NULL,
  "status" "call_status" NOT NULL DEFAULT 'queued',
  "started_at" timestamptz,
  "ended_at" timestamptz,
  "duration_seconds" integer,
  "recording_url" text,
  "recording_path" text,
  "transcript" text,
  "transcript_status" varchar(32) NOT NULL DEFAULT 'pending',
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "calls_twilio_sid_idx" ON "calls" ("twilio_call_sid");
CREATE INDEX "calls_org_idx" ON "calls" ("org_id");
CREATE INDEX "calls_contact_idx" ON "calls" ("contact_id");

CREATE TABLE "sms_messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE SET NULL,
  "deal_id" uuid REFERENCES "deals"("id") ON DELETE SET NULL,
  "phone_number_id" uuid REFERENCES "phone_numbers"("id") ON DELETE SET NULL,
  "twilio_message_sid" varchar(64) NOT NULL,
  "direction" "sms_direction" NOT NULL,
  "from_number" varchar(32) NOT NULL,
  "to_number" varchar(32) NOT NULL,
  "body" text NOT NULL,
  "media_urls" jsonb DEFAULT '[]'::jsonb,
  "status" "sms_status" NOT NULL DEFAULT 'queued',
  "sent_at" timestamptz,
  "delivered_at" timestamptz,
  "read_at" timestamptz,
  "error_code" integer,
  "error_message" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "sms_twilio_sid_idx" ON "sms_messages" ("twilio_message_sid");
CREATE INDEX "sms_org_idx" ON "sms_messages" ("org_id");
CREATE INDEX "sms_contact_idx" ON "sms_messages" ("contact_id");

CREATE TABLE "activities" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "type" "activity_type" NOT NULL,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE CASCADE,
  "deal_id" uuid REFERENCES "deals"("id") ON DELETE CASCADE,
  "ref_id" uuid,
  "summary" text,
  "occurred_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "activities_org_idx" ON "activities" ("org_id");
CREATE INDEX "activities_contact_idx" ON "activities" ("contact_id");
CREATE INDEX "activities_deal_idx" ON "activities" ("deal_id");
CREATE INDEX "activities_type_idx" ON "activities" ("type");

CREATE TABLE "ai_summaries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "activity_id" uuid REFERENCES "activities"("id") ON DELETE CASCADE,
  "summary" text NOT NULL,
  "next_actions" jsonb DEFAULT '[]'::jsonb,
  "sentiment" varchar(16),
  "topics" jsonb DEFAULT '[]'::jsonb,
  "model" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "ai_summaries_activity_idx" ON "ai_summaries" ("activity_id");

CREATE TABLE "ai_drafts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "contact_id" uuid REFERENCES "contacts"("id") ON DELETE CASCADE,
  "author_user_id" varchar(64) REFERENCES "users"("id") ON DELETE SET NULL,
  "prompt" text NOT NULL,
  "retrieved_context_ids" jsonb DEFAULT '[]'::jsonb,
  "draft_body" text NOT NULL,
  "channel" "ai_draft_channel" NOT NULL,
  "model" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "used_at" timestamptz
);
CREATE INDEX "ai_drafts_contact_idx" ON "ai_drafts" ("contact_id");
CREATE INDEX "ai_drafts_org_idx" ON "ai_drafts" ("org_id");

CREATE TABLE "ai_styles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "user_id" varchar(64) NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "examples" jsonb DEFAULT '[]'::jsonb,
  "notes" text,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "ai_styles_user_idx" ON "ai_styles" ("user_id");

CREATE TABLE "lead_scores" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "contact_id" uuid NOT NULL REFERENCES "contacts"("id") ON DELETE CASCADE,
  "score" integer NOT NULL,
  "rationale" text NOT NULL,
  "scored_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "lead_scores_contact_idx" ON "lead_scores" ("contact_id");
CREATE INDEX "lead_scores_org_score_idx" ON "lead_scores" ("org_id", "score");

CREATE TABLE "embeddings" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" varchar(64) NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "source_type" varchar(32) NOT NULL,
  "source_id" uuid NOT NULL,
  "chunk_index" integer NOT NULL DEFAULT 0,
  "content" text NOT NULL,
  "embedding" vector(1024),
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "embeddings_org_source_idx" ON "embeddings" ("org_id", "source_type", "source_id");
-- IVFFlat index for cosine distance (lists tuned for ~1k rows; rebuild at scale)
CREATE INDEX "embeddings_embedding_ivfflat" ON "embeddings"
  USING ivfflat ("embedding" vector_cosine_ops) WITH (lists = 100);

CREATE TABLE "audit_log" (
  "id" serial PRIMARY KEY,
  "org_id" varchar(64) NOT NULL,
  "actor_user_id" varchar(64),
  "action" text NOT NULL,
  "entity" text NOT NULL,
  "entity_id" text,
  "meta" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "audit_org_idx" ON "audit_log" ("org_id");
CREATE INDEX "audit_entity_idx" ON "audit_log" ("entity", "entity_id");
CREATE INDEX "audit_created_idx" ON "audit_log" ("created_at");

-- ─── Single-tenant seed ────────────────────────────────────────────────────────

INSERT INTO "organizations" ("id", "name") VALUES ('kavora', 'Kavora Systems')
  ON CONFLICT ("id") DO NOTHING;

INSERT INTO "pipelines" ("id", "org_id", "name")
  VALUES ('00000000-0000-0000-0000-000000000001', 'kavora', 'Sales')
  ON CONFLICT DO NOTHING;

INSERT INTO "pipeline_stages" ("id", "org_id", "pipeline_id", "name", "order", "is_won", "is_lost", "color") VALUES
  ('00000000-0000-0000-0000-000000000010', 'kavora', '00000000-0000-0000-0000-000000000001', 'Lead',         0, false, false, '#94a3b8'),
  ('00000000-0000-0000-0000-000000000011', 'kavora', '00000000-0000-0000-0000-000000000001', 'Qualified',    1, false, false, '#60a5fa'),
  ('00000000-0000-0000-0000-000000000012', 'kavora', '00000000-0000-0000-0000-000000000001', 'Proposal',     2, false, false, '#a78bfa'),
  ('00000000-0000-0000-0000-000000000013', 'kavora', '00000000-0000-0000-0000-000000000001', 'Negotiation',  3, false, false, '#f59e0b'),
  ('00000000-0000-0000-0000-000000000014', 'kavora', '00000000-0000-0000-0000-000000000001', 'Won',          4, true,  false, '#10b981'),
  ('00000000-0000-0000-0000-000000000015', 'kavora', '00000000-0000-0000-0000-000000000001', 'Lost',         5, false, true,  '#ef4444')
ON CONFLICT DO NOTHING;
